export const dummyData = [
  { id: 0, text: "(Child noises in the background)" },
  { id: 1, text: "Hello, hello?" },
  { id: 2, text: "i need to jump in another call" },
  { id: 3, text: "can anyone go on mute" },
  { id: 4, text: "could you please get closer to the mic" },
  { id: 5, text: "(load painful echo / feedback)" },
  { id: 6, text: "Next Slide, please." },
  { id: 7, text: "can we take this offline?" },
  { id: 8, text: "is __ on call?" },
  { id: 9, text: "Could you share this slides afterwards?" },
  { id: 10, text: "can somebody grant presenter rights?" },
  { id: 11, text: "can you email that to everyone?" },
  { id: 12, text: "CONE CALL BINGO" },
  { id: 13, text: "sorry, i had problems loging in" },
  { id: 14, text: "(animal noises in the background)" },
  { id: 15, text: "sorry, i didn't found the conference id" },
  { id: 16, text: "i was having connectiion issues" },
  { id: 17, text: "i'll have to get back to you" },
  { id: 18, text: "who just joined?" },
  { id: 19, text: "sorry, something __ with my calendar" },
  { id: 20, text: "do you see my screen" },
  { id: 21, text: "lets wait for__!" },
  { id: 22, text: "You will send the minutes?" },
  { id: 23, text: "sorry i was on mute" },
  { id: 24, text: "can you repeat, please?" },
];

export const cardData = [
  [
    { id: 0, text: "(Child noises in the background)" },
    { id: 1, text: "Hello, hello?" },
    { id: 2, text: "i need to jump in another call" },
    { id: 3, text: "can anyone go on mute" },
    { id: 4, text: "could you please get closer to the mic" },
  ],
  [
    { id: 5, text: "(load painful echo / feedback)" },
    { id: 6, text: "Next Slide, please." },
    { id: 7, text: "can we take this offline?" },
    { id: 8, text: "is __ on call?" },
    { id: 9, text: "Could you share this slides afterwards?" },
  ],
  [
    { id: 10, text: "can somebody grant presenter rights?" },
    { id: 11, text: "can you email that to everyone?" },
    { id: 12, text: "CONE CALL BINGO" },
    { id: 13, text: "sorry, i had problems loging in" },
    { id: 14, text: "(animal noises in the background)" },
  ],
  [
    { id: 15, text: "sorry, i didn't found the conference id" },
    { id: 16, text: "i was having connectiion issues" },
    { id: 17, text: "i'll have to get back to you" },
    { id: 18, text: "who just joined?" },
    { id: 19, text: "sorry, something __ with my calendar" },
  ],
  [
    { id: 20, text: "do you see my screen" },
    { id: 21, text: "lets wait for__!" },
    { id: 22, text: "You will send the minutes?" },
    { id: 23, text: "sorry i was on mute" },
    { id: 24, text: "can you repeat, please?" },
  ],
];
